// file generated by go generate

package db

var migrations = []string{
"-- Run the entire migration as an atomic operation.\nSTART TRANSACTION ISOLATION LEVEL SERIALIZABLE READ WRITE;\n\n-- Table apikey holds teams' deploy API keys.\n-- A team can have many API keys, with each key having its own expiry time.\nCREATE TABLE users\n(\n    \"id\"       varchar primary key not null,\n    \"username\" varchar unique      not null,\n    \"token\"    varchar             null\n);\n\n-- Database migration\nCREATE TABLE migrations\n(\n    \"version\" int primary key          not null,\n    \"created\" timestamp with time zone not null\n);\n\n-- Mark this database migration as completed.\nINSERT INTO migrations (version, created)\nVALUES (1, now());\nCOMMIT;\n",

}
