version: "3"
services:
  postgres:
    command: postgres -c log_statement=all
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=gemini"
      - "POSTGRES_PASSWORD=gemini"
      - "POSTGRES_DB=gemini"
