apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: aura
  name: gemini
  namespace: aura
spec:
  image: {{ image }}
  env:
    - name: REDIRECT_URL
      value: https://gemini.nais.io/oauth2/callback
    - name: BIND_ADDRESS
      value: 0.0.0.0:3000
  azure:
    application:
      enabled: true
      tenant: nav.no
  gcp:
    sqlInstances:
    - cascadingDelete: false
      databases:
      - envVarPrefix: DATABASE
        name: gemini
      diskAutoresize: true
      diskSize: 10
      diskType: SSD
      highAvailability: false
      name: gemini
      tier: db-f1-micro
      type: POSTGRES_12
  ingresses:
  - https://gemini.nais.io
  liveness:
    failureThreshold: 3
    path: /metrics
    periodSeconds: 10
    timeout: 1
  port: 3000
  prometheus:
    enabled: true
    path: /metrics
  readiness:
    path: /metrics
  replicas:
    cpuThresholdPercentage: 50
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
