name: Nais build test-pipeline

on:
  push: {}

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Run Nais build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - env:
        RUST_LOG: debug
        WORKLOAD_IDENTITY_POOL: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      run: |
        wget -O /usr/local/bin/nb https://github.com/nais/build/releases/download/v1/nb
        chmod +x /usr/local/bin/nb
        /usr/local/bin/nb release
