name: Gemini release pipeline

on:
  push: {}

jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build and push Docker image
      uses: nais/docker-build-push@main
      id: docker-push
      with:
        team: aura
        project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
    - name: Deploy to NAIS cluster
      uses: nais/deploy/actions/deploy@v2
      if: github.ref == 'refs/heads/master'
      env:
        CLUSTER: prod-gcp
        RESOURCE: nais.yaml
        VAR: image=${{ steps.docker-push.outputs.image }}
        TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}
