name: Gemini release pipeline

on:
  push: {}

jobs:

  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: nais/docker-build-push@v0
      id: docker-push
      with:
        team: aura

  deploy:
    name: Deploy to NAIS
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais.yaml
          VAR: image=${{ steps.docker-push.outputs.image }}
